### ISSUE TITLE
Doesn't compile with Node 0.11.8

### ISSUE THREAD

**Issue by Rob--W** [erikdubbelboer/node-sleep#14]
This package does not compile on my server where Node 0.11.8 is installed.
Here is the relevant error message:

```
  CXX(target) Release/obj.target/node_sleep/sleep.o
../sleep.cc:36:27: error: 'Arguments' does not name a type
../sleep.cc:36:38: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
../sleep.cc: In function 'v8::Handle<v8::Value> Sleep(const int&)':
../sleep.cc:37:15: error: no matching function for call to 'v8::HandleScope::HandleScope()'
../sleep.cc:37:15: note: candidates are:
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note:   candidate expects 1 argument, 0 provided
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note: v8::HandleScope::HandleScope(v8::Isolate*)
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note:   candidate expects 1 argument, 0 provided
../sleep.cc:39:12: error: request for member 'Length' in 'args', which is of non-class type 'const int'
../sleep.cc:39:35: error: invalid types 'const int[int]' for array subscript
../sleep.cc:43:15: error: invalid types 'const int[int]' for array subscript
../sleep.cc: At global scope:
../sleep.cc:48:28: error: 'Arguments' does not name a type
../sleep.cc:48:39: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
../sleep.cc: In function 'v8::Handle<v8::Value> USleep(const int&)':
../sleep.cc:49:15: error: no matching function for call to 'v8::HandleScope::HandleScope()'
../sleep.cc:49:15: note: candidates are:
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note: v8::HandleScope::HandleScope(const v8::HandleScope&)
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:783:3: note:   candidate expects 1 argument, 0 provided
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note: v8::HandleScope::HandleScope(v8::Isolate*)
/home/deploy/.node-gyp/0.11.8/deps/v8/include/v8.h:756:3: note:   candidate expects 1 argument, 0 provided
../sleep.cc:51:12: error: request for member 'Length' in 'args', which is of non-class type 'const int'
../sleep.cc:51:35: error: invalid types 'const int[int]' for array subscript
../sleep.cc:55:16: error: invalid types 'const int[int]' for array subscript
../sleep.cc: In function 'void init(v8::Handle<v8::Object>)':
../sleep.cc:62:41: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [6], v8::Handle<v8::Value> (&)(const int&))'
../sleep.cc:62:41: note: candidate is: 
/home/deploy/.node-gyp/0.11.8/src/node.h:140:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
../sleep.cc:63:43: error: no matching function for call to 'NODE_SET_METHOD(v8::Handle<v8::Object>&, const char [7], v8::Handle<v8::Value> (&)(const int&))'
../sleep.cc:63:43: note: candidate is: 
/home/deploy/.node-gyp/0.11.8/src/node.h:140:13: note: template<class TypeName> void node::NODE_SET_METHOD(const TypeName&, const char*, v8::FunctionCallback)
make: *** [Release/obj.target/node_sleep/sleep.o] Error 1
```
